services:
  redis-test:
    image: redis/redis-stack:7.4.0-v0
    container_name: redis-test
    ports:
      - "${REDIS_EXT_PORT}:${REDIS_PORT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - rewards-network

  rewards-test:
    container_name: rewards-test
    build:
      context: .
      dockerfile: ./.deploy/docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      redis-test:
        condition: service_started
    entrypoint: []
    command:
      - ./scripts/launch-tests.sh
    env_file:
      - .test.env
    networks:
      - rewards-network

networks:
  rewards-network:
    external: true