[pytest]
DJANGO_SETTINGS_MODULE = apirewards.test_settings
norecursedirs = docs/* .venv/* venv/
addopts = -v -s --no-migrations -p no:cacheprovider --cov
python_files = test_*.py
testpaths = tests/
env_files=.test.env
