"""
Django settings for apirewards project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    # Далее в конфиге мы настроим simplejwt так, чтобы он по запросу на обновление
    # access_token возвращал вместе с новым токеном доступа еще и refresh_token.
    # Авторы библиотеки реализовали это так, что старый refresh_token добавляется
    # в черный список и более становится невалидным. Для реализации этого черного
    # списка и используется приложение token_blacklist.
    # Подробнее: https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#blacklist-after-rotation
    "rewards.apps.RewardsConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "apirewards.urls"

CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apirewards.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "USER": config("POSTGRES_USER"),
        "NAME": config("POSTGRES_DB"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("POSTGRESQL_HOST"),
        "PORT": config("POSTGRESQL_PORT"),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "rewards.User"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE")

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S.%f+00:00",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "RS256",
    # Стандартным для simplejwt является использование симметричного алгоритма
    # шифрования HS256, когда шифрование и дешифрование подписи токена осуществляется
    # с помощью единственного ключа.
    # Однако, например, сервис авторизации Keycloak, весьма популярный, к слову,
    # использует несимметричный алгоритм RS256, когда шифрование осуществляется
    # с помощью секретного ключа (о котором знать никто не должен), а вот
    # дешифрование и валидация осуществляются с помощью открытого публичного
    # ключа.
    # Будем придерживаться высоких стандартов аутентификации.

    # Сами ключи будут генерироваться каждый раз при запуске контейнера
    # (ни в коем случае не на этапе создания образа), выгружаться в переменные
    # окружения и оттуда читаться приложением.
    "SIGNING_KEY": config("PRIVATE_KEY"),
    "VERIFYING_KEY": config("PUBLIC_KEY"),
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# Celery & Redis config
REDIS_HOST = config("REDIS_HOST")
REDIS_PORT = config("REDIS_PORT")
REDIS_USER = config("REDIS_USER")
REDIS_PASSWORD = config("REDIS_PASSWORD")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://{}:{}@{}:{}".format(
            REDIS_USER, REDIS_PASSWORD, REDIS_HOST, REDIS_PORT
        ),
        "KEY_PREFIX": "rewards",
    }
}

CELERY_BROKER_URL = "redis://{}:{}@{}:{}/0".format(
    REDIS_USER, REDIS_PASSWORD, REDIS_HOST, REDIS_PORT
)
CELERY_VISIBILITY_TIMEOUT = config("CELERY_VISIBILITY_TIMEOUT", cast=float)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": CELERY_VISIBILITY_TIMEOUT
}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = [config("CELERY_ACCEPT_CONTENT")]
CELERY_TASK_SERIALIZER = config("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = config("CELERY_RESULT_SERIALIZER")
